M48
; DRILL file {KiCad (6.0.2)} date Tue Mar 22 19:35:42 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-22T19:35:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X-35.814Y48.895
X-32.385Y-19.05
X0.0Y-47.625
X32.385Y-19.05
X35.814Y48.895
T0
M30
